### ISSUE TITLE
Question: does this mean Swift frameworks could be deployed to iOS 7?

### ISSUE THREAD

**Issue by mhuusko5** [johnno1962/Accelerator#1]
A big drawback to Swift dynamic frameworks is not being able to target iOS 7.. would this method of static linking be a potential workaround?

**Comment by johnno1962** [comment]
The patching script would needed to be modified to remove the -framework arguments to the linker for the dummy pods or it gives you an error but it seems to work. I’ve just run “eidolon” on an iPad with iOS7.

**Comment by mhuusko5** [comment]
Also, very curious.. Apple not allowing static Swift frameworks seems to have been for a serious reason..

`The current runtime doesn't ship with the OS, so static libs would lead to multiple runtimes in the final executable. A statically linked runtime would be much more difficult to patch for compatibility with newer OS or Swift. — Joe Groff`

.. how are you able to work around this issue? Is it just a matter of making sure all the frameworks build with the same version of Swift?

**Comment by johnno1962** [comment]
I’ve just pushed a modified script which allows deployment to iOS 7.

I’m not sure what you mean by your question though? This is only about moving pod code for which you have the source and forms part of an application out of embedded frameworks and linking them into the main executable. They are all compiled together so there should be no problem.

**Comment by mhuusko5** [comment]
I think that answers my question. Silly me.
