### ISSUE TITLE
Just a question about dynamic linking & static linking

### ISSUE THREAD

**Issue by cezheng** [johnno1962/Accelerator#4]
This project reminds me of an article I read some time ago. http://pewpewthespells.com/blog/static_and_dynamic_libraries.html

It says 

```
Unlike dynamic, linking static libraries includes the object file code from the library into the target's binary. This results in a larger size on disk and slower launch times.
```

Does this means that theoretically dynamic linking will accelerate app's launch but in actually project there are other factors that make static linking to perform better?

**Comment by johnno1962** [comment]
There has been a long discussoin about whether static linking improves launch time and the verdict seems to be that it does if you are using a large number of frameworks due to codesigning. See https://github.com/artsy/eigen/issues/586 for more information.
